project:
  type: website

website:
  title: "Michelle M. Qin"
  navbar:
    search: true
    left:
      - file: index.qmd
        text: "Home"
      - file: about.qmd
        text: "About"
      - file: analysis.qmd
        text: "Example analysis"

format:
  html:
    theme: pulse
    css: styles.css
    toc: false

editor: visual

